env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "prettier"
  - "preact"
parserOptions:
  sourceType: module
rules:
  "react/react-in-jsx-scope": [off]
  quotes:
    - error
    - double
  object-curly-spacing:
    - error
    - always
