language: node_js
node_js:
  - 10.16.3
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.9/terraform_0.12.9_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f /tmp/terraform.zip
install:
  - pushd backend && npm install && popd
  - pushd frontend && npm install && npm run prod && popd
  - cp frontend/dist/* backend/
jobs:
  include:
    - stage: test
      script: pushd backend && npm run test && popd
      env:
        - NODE_ENV=test
        - APP_PORT=8080
    - stage: deploy
      script: ./deploy.sh
      if: branch = master
