env:
  node: true
  es6: true
  commonjs: true
  mocha: true
extends:
  - "eslint:recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
rules:
  quotes:
    - error
    - double
  object-curly-spacing:
    - error
    - always
