env:
  node: true
  es6: true
extends:
  - "eslint:recommended"
  - "prettier"
parserOptions:
  sourceType: module
rules:
  quotes:
    - error
    - double
  object-curly-spacing:
    - error
    - always
